### ISSUE TITLE
Инициализация базы жестко завязана на RU локаль

### ISSUE THREAD

**Issue by pumbaEO** [vanessa-opensource/vanessa-runner#184]
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%98%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%9E%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.os#L236 

Имхо, надо убирать эти строки вообще. Т.к. указание параметра /L для 1С не играент никакой роли при создании базы и в результате ошибка, т.к сообщение в файле на другом языке.

**Comment by artbear** [comment]
уже не актуально, т.к. параметр давно опциональный
