### ISSUE TITLE
Проблема команды session kill с завершеннными сеансами

### ISSUE THREAD

**Issue by arkuznetsov** [vanessa-opensource/vanessa-runner#264]
При выполнении команды session kill происходит ошибка, "Сеанс с указанным идентификатором не найден".
Имеет смысл игнорировать данную ошибку, т.к. требуемый результат команды все равно достигается.

**Comment by artbear** [comment]
Данное исправление не попало в релиз, т.к. залиты исправления не в основной репозиторий
>EvilBeaver added a commit to oscript-library/vanessa-runner that referenced this issue on 17 Dec 2018

и в релиз 1.6.0 от 24.12.2018 это исправление не попало :(

**Comment by artbear** [comment]
Обнаружено на проекте имплементации инженерных практик

сейчас ветка мастер из репо oscript-library с исправлением по ишузу залита в ветку девелоп основного репозитория.

исправление войдет в очередной релиз 1.7.0 ванесса-раннер, который будет выпущен в ближайшие дни.

**Comment by 1cgh** [comment]
начали у себя переводить старые скрипты с deployka на vrunner.
столкнулись тем, что vrunner при session kill падает с ошибкой
21:05:32 КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Классы\КомандаУправлениеСеансами.os / Ошибка в строке: 271 / Попытка удаления сеансов не удалась. Текст ошибки:
21:05:32 Сообщение от процесса 
21:05:32  код:-1 процесс: Сеанс с указанным идентификатором не найден}

при этом отладка показывает для сеанса, при отключении которого происходит ошибка, не тот session-id, который у него фактически

deployka же показывает номер сеанса корректно, сеансы отключает, с ошибкой не падает

**Comment by 1cgh** [comment]
@artbear наблюдается в 1.7.0
не исправляли?

**Comment by SidnevAV** [comment]
@artbear повторяется в vanessa-runner v1.10.0

**Comment by artbear** [comment]
@SidnevAV добавь вот код проверки `Соединение .+ не найдено` через регулярку или двойным найти ("Соединение" и "не найдено"
строка кода
https://github.com/vanessa-opensource/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L599

**Comment by artbear** [comment]
оказывается, я забыл ишуз закрыть.

сейчас проблема новая, конечно, но раз ишуз открыт, то в его рамках и исправим

@SidnevAV написал в ответ на мое предложение - Спасибо, попробую. PR закину если сработает.

**Comment by arkuznetsov** [comment]
Коллеги! Если есть возможность, проверьте на англоязычной платформе, чтоб уж совсем закрыть.

**Comment by SidnevAV** [comment]
Еще такая ошибка проявилась при попытке получить соединения:
`05:03:00  КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Классы\КомандаУправлениеСеансами.os / Ошибка в строке: 283 / Попытка удаления сеансов не удалась. Текст ошибки:`
`05:03:00  Сообщение от процесса`
`05:03:00   код:-1 процесс: Рабочий процесс с указанным идентификатором не найден}`

Дотестирую исправления и закину одним PR.

**Comment by rugubara** [comment]
Коллеги, добавьте в обработку исключений также сообщения об ошибках от RAS на английском. 
У меня валится скрипт 
КРИТИЧНАЯОШИБКА - {Модуль C:\1c\onescript\lib\vanessa-runner\src\Классы\КомандаУправлениеСеансами.os / Ошибка в строке: 294 / Попытка удаления сеансов не удалась. Текст ошибки:
Сообщение от процесса
 код:-1 процесс: Session with the specified ID not found}
