### ISSUE TITLE
EDT сборка

### ISSUE THREAD

**Issue by ghost** [vanessa-opensource/vanessa-runner#275]
https://gist.github.com/zeegin

![default](https://user-images.githubusercontent.com/55323/51741712-c3052680-20a8-11e9-932c-62bb46def62e.png)

Собственно Диме нужно помочь ;-)

**Comment by ZhdanovR** [comment]
Из контекста не ясно что нужно сделать. Проект edt? и из него нужно собрать 1сную базу?
ring edt export - не оно?
