### ISSUE TITLE
Порядок вызова обработчиков оповещения

### ISSUE THREAD

**Issue by Solomasov** [vanessa-opensource/vanessa-runner#303]
При открытии обработки возникает ошибка загрузки плагина "ЗагрузитьПользовательскиеНастройки".

Причина в порядке вызова обработчиков - иногда первым может вызваться обработчик "ПриОткрытииЗавершение" до события "ОбработчикПоискаКлиентскихПлагиновЗавершение".

Релиз платформы: 8.3.13.1809.

![Ошибка](https://user-images.githubusercontent.com/38571673/58618735-0af0c000-82cc-11e9-8c72-c4d3995ea4f3.png)

**Comment by artbear** [comment]
видимо, эта проблема к Ванесса-АДД,
Там эта проблема давно решена.
Закрываю.
