### ISSUE TITLE
Ошибка при LOGOS_CONFIG=logger.rootLogger=DEBUG;

### ISSUE THREAD

**Issue by andrrreasss** [vanessa-opensource/vanessa-runner#314]
После установки переменной  LOGOS_CONFIG=logger.rootLogger=DEBUG;

при запуске runner вываливается ошибка:

{Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\oscript_modules\logos\src\log-manager.os / Ошибка в строке: 74 / Внешнее исключение (System.NullReferenceException): Ссы
лка на объект не указывает на экземпляр объекта.}

**Comment by artbear** [comment]
@EvilBeaver эта проблема решена в 1.1 или 1.2 или еще нет?

ps что-то я пропустил ее решение

**Comment by witales** [comment]
@andrrreasss как это воспроизвести?
попробовал у себя в переменной окружения выставить LOGOS_CONFIG=logger.rootLogger=DEBUG и выполнить runner - ошибки нет.

**Comment by EvilBeaver** [comment]
В 1.2 должна быть решена

**Comment by artbear** [comment]
вроде бы давно решено в движке 1скрипта
