### ISSUE TITLE
Добавить возможность указывать разрядность 

### ISSUE THREAD

**Issue by viskvortsov** [vanessa-opensource/vanessa-runner#316]
Хотелось бы иметь возможность указать разрядность платформы.
На уровне v8runner возможность есть.
В частности интересует шаг tests.
+ возможность указывать разрядность в настройках json

**Comment by artbear** [comment]
Да, хорошее предложение. Нужно сделать.

**Comment by artbear** [comment]
Напрашиваются ключи --32 или -64

без их указания поведение как сейчас.
при их указании ищутся только соответствующие версии.
