### ISSUE TITLE
Создание инф. базы в кластере

### ISSUE THREAD

**Issue by LazarenkoA** [vanessa-opensource/vanessa-runner#319]
Добрый день, подскажите актуальная версия умеет создавать в кластере инф базу? В хелпе не увидел такого, смотрел на версии 1.7.0

**Comment by artbear** [comment]
@LazarenkoA Нет, пока не умеет. 

Странно, неужели никому до сих пор не понадобилось ) ?

между тем, код создания серверных баз давно есть в vanessa-add в файле init.os

Нужно перекинуть этот код в отдельную команду Ванесса-раннер
