### ISSUE TITLE
Разнести логику команд продукта по разным классам вместо одного единого файла

### ISSUE THREAD

**Issue by artbear** [vanessa-opensource/vanessa-runner#33]
Хочется сильно упростить код, разнеся код команд и код исполняемого приложения на разные файлы скриптов, аналогично шаблону по созданию приложений https://github.com/EvilBeaver/oscript-app-template

ИМХО будет проще поддерживать, ревьюить, мержить, тестировать.

**Comment by realMaxA** [comment]
Как быть с тем, что есть init.os и runner.os?
Логично было бы функционал из init.os добавить в runner.os в соответствующие команды.
Стоит это делать?

**Comment by nixel2007** [comment]
Не совсем. Раннер.ос должен вообще остаться запускатором 
А вся прикладная логика должна быть инкапсулирована в другие классы

**Comment by realMaxA** [comment]
Я, собственно это и имел в виду. Отказаться от init.os.
Смотрю, что можно сделать, это же полный рефакторинг всего и вся. Это вообще возможно в рамках данного инструмента? Не потребуется создать что-то вроде vanessa-runner-new?

**Comment by nixel2007** [comment]
Нет, не потребуется. Подобный рефакторинг на днях был проведён для гитсинка.

**Comment by artbear** [comment]
Частично выполнено

**Comment by artbear** [comment]
давным-давно сделано.
