### ISSUE TITLE
Некорректно определяется версия платформы

### ISSUE THREAD

**Issue by acharushkin** [vanessa-opensource/vanessa-runner#376]
**ОС:** Win 10 x64

**Установленные версии платформы:**
32-битная 8.2.19 (c:\Program Files (x86)\1cv82\8.2.19.130)
32-битная 8.3.10 (c:\Program Files (x86)\1cv8\8.3.10.2772)
64-битная 8.3.16 (c:\Program Files\1cv8\8.3.17.1386)

Выполняю команду `vrunner xunit <testsPath> --v8version 8.3`

**Ожидаемое поведение:**
Запускается максимальная версия платформы (64-битная 8.3.16)

**Фактическое поведение:**
Запускается 32-битная 8.3.10

**Comment by artbear** [comment]
@acharushkin странно, до сих пор такое поведение?
вроде бы в пакет в8раннер добавляли улучшали по правильному поиску платформы

**Comment by artbear** [comment]
Добавлена возможность выбора разрядности. см. релиз 1.11.1
Закрываю.
