### ISSUE TITLE
Через команду xunit нельзя передать дополнительные параметры

### ISSUE THREAD

**Issue by acharushkin** [vanessa-opensource/vanessa-runner#377]
Выполняю команду `vrunner xunit --xddconfig myconfig.json --additional myparam`.

Ожидаю, что в командной строке запуска 1С появится ключ `/C myparam`, но это не так.

В параметры запуска 1С передаются только параметры xunit:
```
xddRun ЗагрузчикКаталога \"<testsPath>\"; xddConfig \"<xunit-config.json>\" ;  xddExitCodePath ГенерацияКодаВозврата \"<exitCodePath>\"
```

**Comment by artbear** [comment]
@acharushkin Да, это особенность реализации запуска тестов в хюнит-части.
Наверное, можно и доделать/переделать, не должно быть слишком сложно.

Поделитесь сценарием, что хочется передавать доп.параметром ?

**Comment by ovcharenko-di** [comment]
@artbear я поделюсь своим сценарием: мне требуется указать параметры подключения к отладчику для сбора замеров (и для расчета покрытия)

@acharushkin и я нашел рабочий способ:
указываю эти параметры прямо в json-файле, который передаю в --settings

Вот файл:
```json
{
  "$schema": "https://raw.githubusercontent.com/vanessa-opensource/vanessa-runner/develop/vanessa-runner-schema.json",
  "default": {
    "--db-user": "Администратор",
    "--db-pwd": "",
    "--additional": "/iTaxi /debug -http -attach /debuggerURL \"http://srv-devk-erp01:1550\""
  },
  "xunit": {
    "testsPath": "tests",
    "--pathxunit": "oscript_modules/add",
    "--reportsxunit": "ГенераторОтчетаAllureXMLВерсия2{build/xunit/allure-results/allure.xml}",
    "--xddExitCodePath": "build/xunit/xddExitCodePath.txt",
    "--testclient": "::1538"
  }
}
```

соответственнно, параметр --xddConfig я вообще не указываю, т.к. у меня все в --settings

**Comment by artbear** [comment]
@ovcharenko-di вообще и твой способ, и способ автора - это одна и та же настройка для ванесса-раннера.

вариантом с передачей отладчика давно пользуемся, даже в доке где-то есть примеры.

@acharushkin 
возможно, проблема была решена в девелоп-версии ванесса-раннер, а ты юзал релизную сборку?

**Comment by artbear** [comment]
закрываю как решенное.
