### ISSUE TITLE
[8.3.17] Не удается загрузить и обновить расширение

### ISSUE THREAD

**Issue by KrapivinAndrey** [vanessa-opensource/vanessa-runner#400]
На файловой базе загружается расширение с объектами. 
Команда 
vrunner loadext --settings MySettings.json --file MyExt.cfe --extension Name --updatedb

Заканчивается ошибкой.
```

ОШИБКА - [oscript.lib.v8runner] - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - [o.app.vanessa-runner] - {Модуль C:\usr\OneScript\lib\vanessa-runner\src\Классы\КомандаЗагрузитьРасширениеИзФайла.os / Ошибка в строке: 71 / {Модуль C:\usr\OneScript\lib\vanessa-runner\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1354 / Ошибка в параметрах командной строки.
}
                ВызватьИсключение ВыводКоманды();}
```

Экспериментами выяснил, что проблема в параметре -Server при обновлении базы. Без него расширение загружаются и обновляются.

```
"C:\Program Files (x86)\1Cv8\8.3.17.1549\bin\1cv8.exe" DESIGNER /F"C:\Users\a.krapivin\Documents\1C\!FocusWO" /Out "C:\Users\a.krapivin\AppData\Local\Temp\5uno433f.zm5.tmp\m2e3rpwj.k23.txt" /N"Администратор" /Lru /VLru /DisableStartupMessages /DisableStartupDialogs /UpdateDBCfg -Dynamic- -Server -Extension ДополнительныеОбъектыКонтурФокус
``` 
**выдает ошибку**

```
"C:\Program Files (x86)\1Cv8\8.3.17.1549\bin\1cv8.exe" DESIGNER /F"C:\Users\a.krapivin\Documents\1C\!FocusWO" /Out "C:\Users\a.krapivin\AppData\Local\Temp\5uno433f.zm5.tmp\m2e3rpwj.k23.txt" /N"Администратор" /Lru /VLru /DisableStartupMessages /DisableStartupDialogs /UpdateDBCfg -Dynamic- -Extension ДополнительныеОбъектыКонтурФокус
``` 
**нормально работает**

**Comment by artbear** [comment]
Насколько я понимаю, в https://github.com/oscript-library/v8runner/pull/126 как раз исправлена твоя ошибка.

@KrapivinAndrey проверишь?

**Comment by KrapivinAndrey** [comment]
@artbear Я не очень помню чем кончилось мое расследование.
Но кажется проблема PR не решиться. Проблема вот здесь скорее
https://github.com/oscript-library/v8runner/blob/1d6e72ea118bec5a6941b3e5a5bc6a0a0d601968/src/v8runner.os#L857

**Comment by artbear** [comment]
@KrapivinAndrey Твое исследование помогло, проблема была на сторона v8runner в указанной строке кода.

я улучшил фичи для проверки. теперь они проверяют эту проблему.

осталось выпустить релиз v8runner

**Comment by artbear** [comment]
Релиз v8runner 1.8.0 выпущен
