### ISSUE TITLE
Ошибка команды vanessa-runner session kill

### ISSUE THREAD

**Issue by milanse** [vanessa-opensource/vanessa-runner#418]
Команда падает Версия платформы 8.3.17.1851, рядом 2 базы на этом же сервере и скуле - все работает.

13:43:44  C:\Program Files (x86)\Jenkins\workspace\UpdateProd\FullUpdate\update pu-sgtrans>call vanessa-runner session kill --with-nolock --ras "servername" --db "dbname" --db-user "Администратор" --db-pwd "dbpass" 
13:43:44  vanessa-runner v1.10.0
13:43:45  ИНФОРМАЦИЯ - Отключаю существующие сеансы
13:43:45  ИНФОРМАЦИЯ - Получаю список кластеров
13:43:45  ИНФОРМАЦИЯ - Получаю список баз кластера
13:43:45  ИНФОРМАЦИЯ - Получен УИД базы
13:43:45  ИНФОРМАЦИЯ - Отключаю сеанс: 34594 [СальниковаОВ] (BackgroundJob)
13:43:45  ИНФОРМАЦИЯ - Отключаю сеанс: 55492 [СмирновСЕ] (SrvrConsole)
13:43:46  ИНФОРМАЦИЯ - Отключаю сеанс: 45107 [ТрунинаСЮ] (1CV8C)
13:43:46  ИНФОРМАЦИЯ - Отключаю сеанс: 33243 [ГолубеваЛГ] (1CV8C)
13:43:47  ИНФОРМАЦИЯ - Пауза перед отключением соединений
13:43:57  ИНФОРМАЦИЯ - Получаю список рабочих процессов...
13:43:57  ИНФОРМАЦИЯ - Получаю список соединений рабочего процесса...
13:44:01  КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Классы\КомандаУправлениеСеансами.os / Ошибка в строке: 283 / Попытка удаления сеансов не удалась. Текст ошибки:
13:44:01  Сообщение от процесса
13:44:01   код:-1 процесс: Ошибка при получении значения из базы данных. Возможной причиной является отсутствие установленного Microsoft SQL Server Native Client.}

Ошибка скорее всего тут:  https://github.com/vanessa-opensource/vanessa-runner/blob/84d60252566e443a68bf055f543fc943f2bde874/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L618

Не понятно в чем проблема.

**Comment by artbear** [comment]
@milanse не повторилось? похоже на ошибку rac

пока закрываю.
если повторится, переоткроем
