### ISSUE TITLE
Дополнить описание "vrunner --help syntax-check"

### ISSUE THREAD

**Issue by SidnevAV** [vanessa-opensource/vanessa-runner#420]
Для параметра --mode нужно добавить описание следующих опций:

● -MobileClient ‑ синтаксический контроль модулей в режиме эмуляции среды мобильного клиента;

● -MobileClientStandalone ‑ синтаксический контроль модулей в режиме эмуляции среды мобильного клиента, работающего в автономном режиме;

● -CheckUseSynchronousCalls ‑ режим поиска использования в модулях синхронных методов. Параметр используется только вместе с параметром -ExtendedModulesCheck.

**Comment by artbear** [comment]
Выполнено.
