### ISSUE TITLE
Некорректно передается путь к подсистеме загрузки тестов xunit

### ISSUE THREAD

**Issue by Mity1440** [vanessa-opensource/vanessa-runner#426]
Ошибочное поведение:
Выполняется команда vrunner xunit --settings %путь до настроечного файла%
В настроечном файле указаны в то числе следующие секции
......
 "xunit": {
         ........
         **"--config-tests": "true",**
         **"testsPath":"Метаданные.Подсистемы.ИмяПодсистемыКакойто",**
         "--xdddebug":"true",
         "--xddConfig": "E:/temp/xUnitParams.json",
         "--reportsxunit": "ГенераторОтчетаJUnitXML{build/ServiceBases/junitreport/xdd/xddreport.xml};ГенераторОтчетаAllureXML{build/ServiceBases/allurereport/xdd/allure-testsuite.xml}",
         "--xddExitCodePath": "./%1xddExitCodePath.txt"
     }
........

При попытке запуска тестов через браузер, фреймворк пытается запустить тесты по адресу
"C:\Метаданные.Подсистемы.ИмяПодсистемыКакойто"

**Comment by artbear** [comment]
выполнено.

**Comment by artbear** [comment]
частично связано с правкой Ванесса-АДД https://github.com/vanessa-opensource/add/issues/846
