### ISSUE TITLE
Ошибка при запуске команды xunit из командной строки Windows

### ISSUE THREAD

**Issue by goro781** [vanessa-opensource/vanessa-runner#432]
поставил все пакеты (Vrunner, vanessa-add) выдает ошибку КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Классы\КомандаТестирование_xUnitFor1C.os / Ошибка в строке: 200 / Внешнее исключение (System.ArgumentException): Путь имеет недопустимую форму.} при запуске команды xunit. как можно с ней бороться? Не могу найти информацию по этой ошибке, помогите разобраться пожалуйста.

**Comment by artbear** [comment]
@goro781 нужны подробности проблемы.
какую команду запускаете?
полная строка этой команды?

**Comment by goro781** [comment]
C:\Users\v.safronov> vrunner xunit "C:\Program Files\OneScript\lib\add\tests\smoke\Тесты_ОткрытиеФормКонфигурации.epf" --ibconnection /S1c***\preprod --db-user "........." --db-pwd "***" --path "C:\Program Files\OneScript\lib\add\xddTestRunner.epf" вот полная строка команды

**Comment by goro781** [comment]
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\oscript_modules\cmdline\src\cmdline.os / Ошибка в строке: 441 / Неизвестный параметр в позиции 9 параметр --path
xunit C:\Program Files\OneScript\lib\add\tests\smoke\Тесты_ОткрытиеФормКонфигурации.epf --ibconnection /S1cdev\preprod --db-user Сафронов Виталий --db-pwd 123 --path C:\Program Files\OneScript\lib\add\xddTestRunner.epf }
Это текст ошибки
Формы не управляемые
Описание: "Управление торговлей", редакция 10.3 (10.3.13.2) (http://v8.1c.ru/trade/)
Режим совместимости: Version8_3_17

**Comment by artbear** [comment]
@goro781 в последнем сообщении написано же про ошибку

нет такого параметра --path

есть --pathxunit

**Comment by goro781** [comment]
В 1с не запустился тест хотя окно открылось. Пишет ошибку. Текст ошибки следующий:
Попробуйте повторить операцию. Если ошибка повторится попробуйте перезапустить приложение или обратитесь к администратору приложения или техническому специалисту.
если раскрыть окно то в подробностях текста ошибки пишет следующее:
Значение не является значением объектного типа (Инициализация)
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(65)}:		Плагин.Инициализация(ЭтотОбъект);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(450)}:	ОписанияЗагрузчиков = ОбъектНаСервере.ПолучитьОписанияПлагиновПоТипу(ОбъектНаСервере.ТипыПлагинов.Загрузчик);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(422)}:	ОписанияЗагрузчиков = ПолучитьОписанияЗагрузчиковНаСервере();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(334)}:	ДобавитьКомандыЗагрузчиковНаФорме();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(328)}:	ЗагрузкаПлагиновЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(303)}:	ПодключитьНайденныеКлиентскиеПлагины(ПомещенныеФайлы, ДополнительныеПараметры.ИдентификаторыПлагинов);

Подскажите что можно предпринять в таком случае?

**Comment by artbear** [comment]
закрываю как устаревший.

Автор, извини (
