### ISSUE TITLE
Не работает runner xunit

### ISSUE THREAD

**Issue by CRCx86** [vanessa-opensource/vanessa-runner#434]
Добрый день! Не работает runner xunit.

Команда запуска тестов:
```
echo Запуск тестов
call runner xunit "%GIT_PATH%\UnitTests" --pathxunit "%pathxunit%" --v8version %version1c% --ibconnection /F"%DEST_PATH%\build\ib" --reportsxunit "ГенераторОтчетаAllureXMLВерсия2{D:\git_projects\allure\merch.xml}"
```

Разворачивается в:
```
call runner xunit "d:\git_projects\ff_test\UnitTests" --pathxunit "C:\Program Files\OneScript\lib\add\xddTestRunner.epf" --v8version 8.3.17.1851 --ibconnection /F"D:\git_projects\xunit\ff\build\ib" --reportsxunit "ГенераторОтчетаAllureXMLВерсия2{D:\git_projects\allure\merch.xml}" 
vanessa-runner v1.10.2
```

Результат:
`
ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка Vanessa-ADD (Vanessa Automation Driven Development) - d:\git_projects\ff_test\UnitTests
ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
ИНФОРМАЦИЯ - Выполнение команды/действия в режиме 1С:Предприятие завершено.
ИНФОРМАЦИЯ - Выполнение тестов завершено
`
Но целевого файла merch.xml в каталоге нет и добавлен тест в котором:
`
Успех = Ложь;
Ожидается.Что(Успех,"Успех").ЕстьИстина();
`
Что говорит о том, что тесты не выполняются

Далее:
При попытке добавить команду 
`
--xddExitCodePath "d:\allure.txt"
`
Падаю с ошибкой:
`
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Классы\МенеджерКонфигуратора.os / Ошибка в строке: 286 / Получен неожиданный/неверный результат работы - Не найден файл статуса d:\allure.txt
Возможна, работа 1С:Предприятие завершилась некорректно.}
`

**Comment by artbear** [comment]
видимо, уже неактуально.
закрываю.

Автор, переоткрывай, если еще нужно.
