### ISSUE TITLE
ошибка при проверке syntax-check

### ISSUE THREAD

**Issue by goro781** [vanessa-opensource/vanessa-runner#440]
При проверки на синтаксис 1С:Предприятие 8.3 (8.3.17.1549) с помочью vannessa-runner Выдает следующую ошибку:
vanessa-runner v1.10.2
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Модули\ОбщиеМетоды.os / Ошибка в строке: 398 / Внешнее исключение (System.NotSupportedException): Данный формат пути не поддерживается.}
Запрос делается из командной строки.
Запрос: 

C:\Users\v.safronov>vrunner syntax-check --ibconnection /S1*****\d********** --db-user "***********" --db-pwd "*****"  --allure-results2 "ГенераторОтчетаAllureXMLВерсия2{C:\Users\v.safronov\Desktop\programms\allure-2.13.3\reports\ШаблонГенератораОтчета.xml}" --pathjunit "C:\Program Files\OneScript\bin\build\allure" --junitConfig "C:\Program Files\OneScript\lib\vanessa-runner\examples\example.env.json" --ordinaryapp 1 --settings "C:\Users\v.safronov\Desktop\programms\add-6.6.5\tools\json\vrunner.json" --debuglogfile "C:\Users\v.safronov\Desktop\programms\vrunner_log_syntax\vrunner-syntax.log" --groupbymetadata --mode -ExternalConnection -IncorrectReferences -ExternalConnectionServer -ConfigLogIntegrity -ExtendedModulesCheck -DistributiveModules -UnreferenceProcedures -HandlersExistence -EmptyHandlers -ExtendedModulesCheck -CheckUseModality -UnsupportedFunctional -ThickClientManagedApplication -ThickClientOrdinaryApplication -ThickClientServerOrdinaryApplication -ThickClientServerManagedApplication 1 -Server /S1*****\d**********
Формы не управляемые.
Прошу помочь в решении этого вопроса.

**Comment by goro781** [comment]
Проблему решил

**Comment by nvtoroy** [comment]
> Проблему решил

каким образом?
