### ISSUE TITLE
Ошибка  Illegal characters in path

### ISSUE THREAD

**Issue by nvtoroy** [vanessa-opensource/vanessa-runner#479]
Доброго дня.
При запуске команды (ниже) в консоли получаю ошибку:
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\main.os / Ошибка в строке: 159 / Внешнее исключение (System.ArgumentException): Illegal characters in path.}

```
runner vanessa --settings tools/vrunner.json --ibconnection "/S1CAPP\1c-sandbox" --db-user *** --db-pwd *** --pathvanessa tools/add/bddRunner.epf
```
Запускаю соответственно из папки, в которой есть папка tools со всем необходимым
Что за такие Illegal characters  и в каком пути они присутствуют?

**Comment by artbear** [comment]
Включи полный лог 
SET LOGOS_LEVEL=DEBUG

Запусти команду повторно в этом же терминале
и приложи файл лога

оперативную помощь лучше общаться в чате проекта в телеграме https://t.me/vanessa_opensource_chat
приходи

**Comment by nvtoroy** [comment]
> Включи полный лог SET LOGOS_LEVEL=DEBUG
> 
> Запусти команду повторно в этом же терминале и приложи файл лога
> 
> оперативную помощь лучше общаться в чате проекта в телеграме https://t.me/vanessa_opensource_chat приходи

Простите, а где полный лог включается?

**Comment by nvtoroy** [comment]
@artbear добавился в группу, решил задачку, начал писать и сразу выкинуло, больше не пускает 0_о
