### ISSUE TITLE
Ошибки в команде "СохранитьВерсиюХранилищаВФайл", если не передается строка соединения

### ISSUE THREAD

**Issue by Borisskin** [vanessa-opensource/vanessa-runner#508]
1. КомандаСохранитьВерсиюХранилищаВФайл.os строка 64 - изменение фиксированной структуры
`ДанныеПодключения.СтрокаПодключения = "/F";`
СтрокаПодключения должна быть заполнена, иначе будет исключение при инициализации МенеджерКонфигуратора

2. Если ДанныеПодключения для исправления ошибки 1 передать обычной структурой - не создаст временную файловую базу, т.к. не будет выполнено условие строки 847 (в строке соединения передали "/F")
`Если Не ЗначениеЗаполнено(КонтекстБД.КлючСоединенияСБазой) Тогда`
у себя добавил проверку/костыль в условие `или СтрДлина(КонтекстБД.КлючСоединенияСБазой) <= 2`

**Comment by artbear** [comment]
Таких проблем еще больше, в 4 классах встречается подобное.
Искать в исходниках регулярку `ДанныеПодключения\.СтрокаПодключения\s*=\s*`

![image](https://user-images.githubusercontent.com/2920817/162039796-3181f6ec-ce3c-4fd2-a7cb-096a5a8f26e9.png)
