### ISSUE TITLE
Некорректная работа ключа --additional-keys

### ISSUE THREAD

**Issue by akademik1986** [vanessa-opensource/vanessa-runner#512]
При использовании ключа --additional-keys на текущий момент приходится передавать в начале строки разделитесь ;  чтобы произошла правильная склейка командной строки.
Рабочий вариант сейчас выглядит так
![image](https://user-images.githubusercontent.com/19662685/166885977-7663a87a-248a-4ffe-bc28-16531cc68aed.png)

Если не передавать разделитель,  то результат такой
![image](https://user-images.githubusercontent.com/19662685/166885898-2d789156-c233-47cb-8976-fc93fdbe5e57.png)

**Comment by yukon39** [comment]
Исправлено в #557  #556
