### ISSUE TITLE
Лишние символы в команде set-version

### ISSUE THREAD

**Issue by Gonchi88** [vanessa-opensource/vanessa-runner#519]
Добрый день, я пробовала команду set-version --src H:\ --new-version 2.1.301.1 (предыдущая версия была 2.1.300.2), лог выдается:
ИНФОРМАЦИЯ - Изменяю версию в исходниках конфигурации или внешнего файла 1С на 2.1.301.1 - H:\
ПРЕДУПРЕЖДЕНИЕ - Найдены xml-исходники внешних обработок\отчетов 1С, но в команде не указан вариант указания версии.
ИНФОРМАЦИЯ -     Старая версия 1.300.2, файл - H:\Configuration.xml 

И в итоге в файле Configuration.xml, версия получается <Version>2. 2.1.301.1</Version>,т.е. с лишней двойкой в начале.
Возможно проблема в файле МенеджерВерсийФайлов1С, строка 232

**Comment by artbear** [comment]
Проблема была в неверном файле релиза, попавшем в хаб оскрипта.
Я выложил правильный файл, автор сообщила, что тикет решен.
Закрываю.
