### ISSUE TITLE
edt-validate ошибка генерации отчета

### ISSUE THREAD

**Issue by jmpjck** [vanessa-opensource/vanessa-runner#529]
ИНФОРМАЦИЯ - Начало проверки EDT-проекта
ИНФОРМАЦИЯ - Проверка EDT-проекта завершена за 853с
ИНФОРМАЦИЯ - Генерация отчета Allure
ИНФОРМАЦИЯ - Генерация отчета Allure2
КРИТИЧНАЯОШИБКА - {Модуль C:\OneScript\lib\vanessa-runner\src\Модули\ГенерацияОтчетов.os / Ошибка в строке: 312 / Преобразование к типу 'Булево' не поддерживается}

**Comment by artbear** [comment]
Исправлено в девелоп-версии
