### ISSUE TITLE
Портировать bootstrap

### ISSUE THREAD

**Issue by ghost** [vanessa-opensource/vanessa-runner#64]
WIP

- [x] создать команду `vboots` позволяющую подготавливать репозиторий
- [ ] включить по умолчанию создание структуры каталогов аналогично https://github.com/silverbulleters/vanessa-bootstrap
- [ ] реализовать создание с нуля
- [ ] реализовать обновление
- [ ] реализовать интерактивное создание через вопросы-ответ пользователя

выпуск
- [ ] оповестить о релизе
- [ ] включить в пакет на хабе
- [ ] оповестить пользователей о `deprecated` для `vanessa-bootstrap` проекта
- [ ] закрыть задачу https://github.com/silverbulleters/vanessa-bootstrap/issues/8

ну и конечно `incorporate alien techs`

**Comment by nixel2007** [comment]
Ты хочешь включить это внутрь раннера?

**Comment by artbear** [comment]
Уже реализовано в https://github.com/vanessa-opensource/vanessa-runner/pull/449
