### ISSUE TITLE
Заменить параметр --ibname на более соответствующее наименование

### ISSUE THREAD

**Issue by artbear** [vanessa-opensource/vanessa-runner#99]
Сейчас `--ibname` это не имя базы, а строка подключения к базе, например, `/Sserver/base` или `/Fc:\ib`

В связи с "обманчивым" наименованием пользователи часто ошибаются и подставляют путь к базе через начальных /S или /F
и при этом выполняется какая-то работа, что ведет к странным ошибками :)

Лучше поменять наименование этого параметра
Например, на `--ibpath`

@nixel2007 для совместимости можно оставить `--ibname` в дополнение к `--ibpath`

- [ ] в доке приложения параметр `--ibname` пометить как устаревший

- [ ] при вызове этого параметра выводить БАЛЬШИМИ :) буквами - УСТАРЕЛ или что-то подобное

**Comment by pumbaEO** [comment]
Я внутренее против изменения, проблема возникла именно в инициализации, т.к. в результате ранних преобразований в СозданиеБазыДанных мы передаем не /F..... , а /Ibname .... в результате изменение кода передачи в создание базы данных исходной строки подключения не ломает ничего. А объявление  --ibname deprecated - ломает.

**Comment by artbear** [comment]
давно сделано.
